version: 0.2

phases:
  install:
    commands:
      - python3 -m venv docker_env && source docker_env/bin/activate && pip install --upgrade pip && pip install --upgrade zappa && pip install -r requirements-prod.txt && zappa update && deactivate && rm -rf docker_env
